alias: 'Telegram command lights on'
initial_state: 'on'
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/lights'
condition:
  - condition: template
    value_template: "{{ (trigger.event.data.args|length == 1) and (trigger.event.data.args[0] == 'on') }}"
action:
  - service: telegram_bot.send_message
    data_template:
      message: >
        Turning the lights {{ trigger.event.data.args[0] }}
