initial_state: 'on'
alias: 'Weather notification'
trigger:
  - platform: time_pattern
    minutes: '/5'
    seconds: '50'
condition:
  - condition: state
    entity_id: input_boolean.living_room_occupied
    state: 'on'
action:
  - service: notify.lm_notify
    data_template:
      message: >-
        {{ states('sensor.dark_sky_temperature')|round(0) }}C outside and {{ states('sensor.dark_sky_minutely_summary')|lower }} {{ states('sensor.dark_sky_hourly_summary') }}
        {% if (not is_state('sensor.dark_sky_alerts','0')) and (states('sensor.dark_sky_alerts') != "unknown") %}. There are weather alerts {% endif %}
