- platform: mqtt
  name: "Garden lights switch"
  state_topic: 'homeassistant/switch/garden_lights_switch/state'
  command_topic: 'homeassistant/switch/garden_lights_switch/command'
  payload_on: 'on'
  payload_off: 'off'
  unique_id: 'zwave-garden_lights_switch'
