- platform: mqtt
  name: "Hall downstairs switch"
  state_topic: 'homeassistant/switch/hall_downstairs_switch/state'
  command_topic: 'homeassistant/switch/hall_downstairs_switch/command'
  payload_on: 'on'
  payload_off: 'off'
  unique_id: 'zwave-hall_downstairs_switch'
