- platform: mqtt
  name: "Master bedroom socket switch"
  state_topic: 'homeassistant/switch/master_bedroom_socket_switch/state'
  command_topic: 'homeassistant/switch/master_bedroom_socket_switch/command'
  payload_on: 'on'
  payload_off: 'off'
  unique_id: 'zwave-master_bedroom_socket_switch'
