- platform: mqtt
  name: "Spare socket switch"
  state_topic: 'homeassistant/switch/spare_socket_switch/state'
  command_topic: 'homeassistant/switch/spare_socket_switch/command'
  payload_on: 'on'
  payload_off: 'off'
  unique_id: 'zwave-spare_socket_switch'
