- platform: mqtt
  name: "Table light switch"
  state_topic: 'homeassistant/switch/table_light_switch/state'
  command_topic: 'homeassistant/switch/table_light_switch/command'
  payload_on: 'on'
  payload_off: 'off'
  unique_id: 'zwave-table_light_switch'
