alias: Dimmer
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.dimmer_switch_action
condition:
  - condition: template
    value_template: "{{ trigger.to_state.state == trigger.to_state.attributes.action }}"
action:
  - service: notify.logfile
    data_template:
      message: "The following button was pressed: {{ trigger.to_state.state }} - {{ trigger.to_state.attributes.action }}"
