alias: Dimmer off
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.dimmer_switch_action
    to: 'off-press'
condition:
  - condition: template
    value_template: "{{ trigger.to_state.state == trigger.to_state.attributes.action }}"
  - condition: template
    value_template: "{{ is_state_attr('sensor.dimmer_switch_action','action','off-press') }}"
  - condition: state
    entity_id: input_boolean.living_room_occupied
    state: 'on'
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.living_room
      option: >-
        {% if is_state('input_select.living_room','Dim') %}
          Off
        {% elif is_state('input_select.living_room','Day on') %}
          Dim
        {% elif is_state('input_select.living_room','Night on') %}
          Day on
        {% else %}
          Off
        {% endif %}

