alias: Dimmer down while on
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.dimmer_switch_action
    to: 'down_press'
condition:
  - condition: state
    entity_id: light.living_room_table
    state: 'on'
action:
  # Make it brighter
  - service: script.living_room_table_dim_step
