homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  #time_zone: Etc/UTC

  customize: !include customize.yaml



config:

frontend: !include frontend.yaml

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
  include_used_components: true

discovery:


conversation:

history:

logbook:

sun:

recorder:
  db_url: sqlite:///data/homeassistant/homeassistant.sqlite
  purge_interval: 2
  purge_keep_days: 4

tts:
  platform: google

zwave:
  usb_path: /dev/ttyAMA0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
  #config_path: /home/.homeassistant/homeassistant/
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key

media_player: !include media_player.yaml

notify: !include_dir_merge_list notify/

google: !include google.yaml

sensor: !include_dir_merge_list sensors/

binary_sensor: !include_dir_merge_list binary_sensors/

light: !include_dir_merge_list light/

switch: !include_dir_merge_list switch/

device_tracker: !include device_tracker.yaml


zone: !include zones.yaml

proximity: !include_dir_merge_named proximity/ 

automation: !include automations.yaml

automation old: !include_dir_list automation/

scene: !include_dir_list scenes/

group: !include groups.yaml

script: !include_dir_named scripts/

input_number: !include input_number.yaml

input_boolean: !include input_boolean.yaml

alert: !include alerts.yaml

emulated_hue:
  listen_port: 80
  host_ip: 192.168.0.10
  exposed_domains:
    - light
    - switch


panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

lametric:
  client_id: !secret lametric_id
  client_secret: !secret lametric_secret

camera: !include_dir_list camera/

variable_int: !include variable_int.yaml

variable_bool: !include variable_bool.yaml
