homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  #time_zone: Etc/UTC
  customize: !include customize.yaml



config:

map:

frontend: !include frontend.yaml

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
  include_used_components: true

discovery:


conversation:

history:

logbook:

recorder:
  db_url: sqlite:///data/homeassistant/homeassistant.sqlite
  purge_interval: 2
  purge_keep_days: 4

tts:
  platform: google

zwave:
  usb_path: /dev/ttyAMA0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: pi3HA


device_tracker: !include device_tracker.yaml

zone: !include zones.yaml

proximity: !include_dir_merge_named proximity/ 


notify: !include_dir_merge_list notify/

alert: !include alerts.yaml

lametric:
  client_id: !secret lametric_id
  client_secret: !secret lametric_secret


google: !include google.yaml


sensor: !include_dir_merge_list sensors/

binary_sensor: !include_dir_merge_list binary_sensors/

sun:

camera: !include_dir_list camera/


input_number: !include input_number.yaml

input_boolean: !include input_boolean.yaml

variable_int: !include variable_int.yaml

variable_bool: !include variable_bool.yaml


light: !include_dir_merge_list light/

switch: !include_dir_merge_list switch/

media_player: !include media_player.yaml


script: !include_dir_named scripts/

automation: !include automations.yaml

automation old: !include_dir_list automation/

scene: !include_dir_list scenes/

group: !include groups.yaml



panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml



google_assistant:
  project_id: !secret assistant_project_id
  client_id: !secret assistant_client_id
  access_token: !secret assistant_access_token
