homeassistant:
  # Name of the location where Home Assistant is running
  name: The House
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  #time_zone: Etc/UTC
  customize: !include customize.yaml

#introduction:

#logger:

config:

map:

frontend: !include frontend.yaml

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
  include_used_components: true

discovery:

#zeroconf:

conversation:

history:

logbook:

recorder:
  db_url: sqlite:///data/homeassistant/homeassistant.sqlite
  purge_interval: 2
  purge_keep_days: 7

tts:
  platform: google

zwave:
  usb_path: /dev/ttyAMA0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key

mqtt:
  broker: 127.0.0.1

mqtt_eventstream:
  publish_topic: master/topic
  subscribe_topic: slaves/#

####################

#device_tracker: !include device_tracker.yaml
device_tracker: !include_dir_list device_tracker/

zone: !include zones.yaml

proximity: !include_dir_merge_named proximity/ 

####################

notify: !include_dir_merge_list notify/

#alert: !include alerts.yaml
alert: !include_dir_named alerts/

lametric:
  client_id: !secret lametric_id
  client_secret: !secret lametric_secret

####################

google: !include google.yaml

####################

sensor: !include_dir_merge_list sensors/

binary_sensor: !include_dir_merge_list binary_sensors/

sun:

camera: !include_dir_list camera/

#ffmpeg:

####################

#input_number: !include input_number.yaml
input_number: !include_dir_named input_number/

#input_boolean: !include input_boolean.yaml
input_boolean: !include_dir_named input_boolean/

#input_select: !include input_select.yaml
input_select: !include_dir_named input_select/

####################

light: !include_dir_merge_list light/

switch: !include_dir_merge_list switch/

#media_player: !include media_player.yaml
media_player: !include_dir_merge_list media_player/ 

####################

script: !include_dir_named scripts/

automation: !include automations.yaml

automation old: !include_dir_list automation/

scene: !include_dir_list scenes/

group: !include groups.yaml

shell_command: !include_dir_merge_named shell_commands/

####################

#datadog:

panel_iframe: !include_dir_merge_named panel_iframe/

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml

alarm_control_panel:
  - platform: manual
    name: "HA Alarm"
    code: !secret alarm_code
    pending_time: 60
    trigger_time: 120
    delay_time: 30
    disarm_after_trigger: false
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

####################

#zoneminder:

google_assistant: !include google_assistant.yaml

dialogflow:

#intent_script: !include intent_scripts.yaml
intent_script: !include_dir_named intent_scripts/
