title: Our Home
views:
  - title: Overview
    id: overview
    cards:
      - type: entity-filter
        entities:
          - binary_sensor.front_door_sensor
          - entity: binary_sensor.garage_closed_bike_sensor
            name: bike
          - entity: binary_sensor.garage_closed_car_sensor
            name: Car
          - entity: binary_sensor.patio_door_left_sensor
            name: Patio door
          - entity: binary_sensor.utility_door_exterior_sensor
            name: Utility
        state_filter:
          - 'on'
        card:
          type: glance
          title: Open doors
      - type: glance
        title: People
        entities:
          - input_select.person3_status_dropdown
          - input_select.person1_status_dropdown
          - input_select.person2_status_dropdown
      - type: glance
        title: Living room
        entities:
          - switch.tv_light_switch
          - switch.cabinet_light_switch
          - switch.table_light_switch
          - entity: switch.livingroom_socket_switch
            name: "Socket"
          - entity: binary_sensor.patio_door_left_sensor
            name: "Patio door"
          - entity: binary_sensor.living_room_motion
            name: "Motion"
          - entity: sensor.living_room_multi_temperature
            name: "Temperature"
          - entity: sensor.living_room_multi_luminance
            name: "Light level"
      - type: glance
        title: Family room
        entities:
          - entity: sensor.person1
            name: XBox
          - entity: device_tracker.family_tv
            name: TV
          - entity: media_player.family_room
            name: Sonos
          - entity: media_player.cast_kitchen_speaker
            name: Home Mini
          - entity: switch.family_room_socket_switch
            name: Socket
      - type: glance
        title: Utility room & outside
        entities:
          - entity: binary_sensor.utility_door_exterior_sensor
            name: Door
          - switch.garden_lights_switch
      - type: glance
        title: Hall and front
        entities:
          - binary_sensor.front_door_sensor
          - entity: switch.hall_downstairs_switch
            name: Hall lights
          - entity: switch.vestibule_switch
            name: Vestibule switch
          - switch.number_sign_switch
      - type: glance
        title: Office
        entities:
          - entity: media_player.office
            name: Sonos
          - entity: media_player.cast_office_speaker
            name: Home Mini
          - entity: sensor.office_multi_temperature
            name: Temperature
          - entity: sensor.office_multi_luminance
            name: Light level
      - type: glance
        title: Master bedroom
        entities:
          - entity: light.master_bedroom_bedhead
            name: Bedhead
          - entity: media_player.person2
            name: Alarm
          - entity: media_player.cast_master_bedroom_speaker
            name: Home Mini
  - title: Rooms
    id: rooms
    icon: mdi:floor-plan
    cards:
      - type: picture-glance
        title: "Who's Home"
        image: /local/images/house.jpg
        entities:
          - input_boolean.person3_home
          - input_boolean.person1_home
          - input_boolean.person2_home
        state_image: 
          "on": /local/images/house.jpg
          "off": /local/images/house.jpg
        entity: input_boolean.all_away
      - type: picture-glance
        image: /local/images/living_room_day.jpg
        title: Living room
        entities:
          - switch.cabinet_light_switch
          - switch.table_light_switch
          - switch.tv_light_switch
          - switch.livingroom_socket_switch
          - binary_sensor.living_room_motion
        state_image: 
          "above_horizon": /local/images/living_room_day.jpg
          "below_horizon": /local/images/living_room_day.jpg
        entity: sun.sun
  - title: Who's where
    id: map
    icon: mdi:google-maps
    cards:
      - type: map
        aspect_ratio: 100%
        entities:
          - device_tracker.person3_mobile
      - type: map
        aspect_ratio: 100%
        entities:
          - device_tracker.person1_mobile
      - type: map
        aspect_ratio: 100%
        entities:
          - device_tracker.person2_mobile
  - title: Media players downstairs
    id: media_downstairs
    icon: mdi:movie
    cards:
      - type: media-control
        entity: media_player.samsung_tv_remote
      - type: media-control
        entity: media_player.cast_living_room_tv
      - type: media-control
        entity: media_player.living_room
      - type: media-control
        entity: media_player.cast_living_room_speaker
      - type: media-control
        entity: media_player.family_room
      - type: media-control
        entity: media_player.cast_kitchen_speaker
  - title: Media players upstairs
    id: media_upstairs
    icon: mdi:speaker
    cards:
      - type: media-control
        entity: media_player.office
      - type: media-control
        entity: media_player.cast_office_speaker
      - type: media-control
        entity: media_player.person1
      - type: media-control
        entity: media_player.cast_second_bedroom_speaker
      - type: media-control
        entity: media_player.person2
      - type: media-control
        entity: media_player.cast_master_bedroom_speaker
      - type: media-control
        entity: media_player.cast_guest_bedroom_speaker
