alias: 'person1 radio off'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.person1
    to: 'off'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.yeelight_strip1_7811dca22b87
      state: 'on'
    - condition: time
      after: '09:59:59'
      before: '21:00:00'
action:
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_7811dca22b87
      transition: 10
  - delay: '00:00:30'
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_7811dca22b87
      transition: 10
