initial_state: 'on'
alias: 'Motion hook'
trigger:
  - platform: webhook
    webhook_id: !secret slack_pi3
action:
  - service: notify.logfile
    data_template:
      message: >
        Triggered by {{ trigger.webhook_id }}  
        Full data: {{ trigger.json }}
