alias: 'Stop stream to living room'
initial_state: 'off'
trigger:
  - platform: state
    entity_id: input_boolean.test_mode
    to: 'off'
action:
  - service: media_player.turn_off
    data:
      entity_id: "media_player.living_room_smart_displa"
