alias: 'Stream to living room'
initial_state: 'off'
trigger:
  - platform: state
    entity_id: input_boolean.test_mode
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.living_room_occupied
    state: 'on'
action:
  - service: camera.play_stream
    data:
      entity_id: "camera.front"
      media_player: "media_player.living_room_smart_displa"
      format: "hls"
