initial_state: 'on'
alias: 'Living room lights dim on'
trigger:
  - platform: state
    entity_id: input_select.living_room
    to: 'Dim'
  - platform: state
    entity_id: input_select.house
    to: 'Dim'
condition:
  # Lighting automations must be enabled
  - condition: state
    entity_id: input_boolean.lighting_automations
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.living_room
      state: 'Dim'
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.living_room
        state: 'Auto'
      - condition: state
        entity_id: input_select.house
        state: 'Dim'
action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.livingroom_lights_auto
  - service: light.turn_on
    data:
      entity_id: light.living_room_table
      brightness_pct: 5
      transition: 15
  - service: switch.turn_on
    entity_id: switch.pi3_livingroom_socket_switch
