initial_state: 'on'
alias: 'person3 location update'
trigger:
  # I've moved
  - platform: state
    entity_id: device_tracker.person3_mobile
action:
  - service: notify.logfile
    data_template:
      message: >
        Location for person3 updated at {{ now() }}
  - service: script.person3_travel_sensor
