alias: 'Bedhead light dim off'
initial_state: 'off'
trigger:
  - platform: time
    at: '22:15:00'
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: light.yeelight_strip1_286c07afc307
        state: 'off'
      - condition: template
        value_template: "{{ state_attr('light.yeelight_strip1_286c07afc307', 'brightness')|default(0)|int > 120 }}"
action:
  - service: switch.turn_off
    entity_id: switch.circadian_lighting_circadian_master_bedroom
  - service: light.turn_on
    data:
      entity_id: light.yeelight_strip1_286c07afc307
      brightness: 120
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_286c07afc307
  - delay: '00:00:01'
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_286c07afc307
