alias: 'Bedhead light dim sunset off'
initial_state: 'off'
trigger:
  platform: sun
  event: sunset
condition:
  condition: state
  entity_id: light.yeelight_strip1_286c07afc307
  state: 'off'
action:
  - service: light.turn_on
    data:
      entity_id: light.yeelight_strip1_286c07afc307
      brightness: 255
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_286c07afc307
  - delay: '00:00:01'
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_286c07afc307
