alias: 'Bedhead light dim'
initial_state: 'on'
trigger:
  - platform: time
    at: '22:15:00'
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: light.yeelight_strip1_286c07afc307
        state: 'on'
      - condition: template
        value_template: "{{ state_attr('light.yeelight_strip1_286c07afc307', 'brightness')|default(0)|int > 120 }}"
action:
  - service: light.turn_on
    data:
      entity_id: light.yeelight_strip1_286c07afc307
      brightness: 120
      transition: 30
