alias: 'Bedhead light on morning'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: light.yeelight_strip1_286c07afc307
    to: 'on'
condition:
  - condition: time
    after: '06:45:00'
    before: '12:00:00'
action:
  - service: light.turn_on
    data:
      entity_id: light.yeelight_strip1_286c07afc307
      color_name: "white"
      brightness: 255
