initial_state: 'on'
alias: 'Living room off'
trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    above: 70
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    above: 50
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    above: 35
    for:
      minutes: 10
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
  - platform: state
    entity_id: input_boolean.living_room_occupied
    to: 'on'
condition:
  # Either it's bright, or the room is empty
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.home_occupied
      state: 'on'
    - condition: state
      entity_id: input_boolean.living_room_occupied
      state: 'on'
    - condition: template
      value_template: "{{ not is_state('input_select.living_room','Off') }}"
    - condition: or
      conditions:
        # The room is currently away
      - condition: state
        entity_id: input_select.living_room
        state: 'Away'
        # Bright, or...
      - condition: numeric_state
        entity_id: sensor.living_room_multi_luminance
        above: 50
      - condition: and
        conditions:
          # Sun is rising and not so bright
        - condition: state
          entity_id: binary_sensor.trend_sun_elevation
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.living_room_multi_luminance
          above: 25
action:
  - service: notify.logfile
    data_template:
      message: >
        Off triggered at {{ now() }} by {{ trigger.entity_id }}, was {{ trigger.from_state.state }} is {{ trigger.to_state.state }}
          Light level is {{ states('sensor.living_room_multi_luminance') }}
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room
      option: 'Off'
