alias: Living room dim
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'off'
  # Home and the room is getting dark
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    below: 5
condition:
  - condition: state
    entity_id: input_boolean.living_room_occupied
    state: 'off'
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.input_boolean.living_room_occupied.last_updated)) | int > 600 }}"
  - condition: state
    entity_id: input_boolean.home_occupied
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.living_room_multi_luminance
    below: 5
  - condition: template
    value_template: "{{ not is_state('input_select.living_room','Dim') }}"
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'off'
action:
  - service: notify.logfile
    data_template:
      message: >
        Dim triggered at {{ now() }} by {{ trigger.entity_id }}, was {{ trigger.from_state.state }} is {{ trigger.to_state.state }}
          Light level is {{ states('sensor.living_room_multi_luminance') }}
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room
      option: 'Dim'
