initial_state: 'on'
alias: 'Living room off empty'
trigger:
  - platform: state
    entity_id: input_boolean.living_room_occupied
    to: 'off'
condition:
  # Home occupied
  - condition: state
    entity_id: input_boolean.home_occupied
    state: 'on'
  # Not currently Off
  - condition: template
    value_template: "{{ not is_state('input_select.living_room','Off') }}"
action:
  - service: notify.logfile
    data_template:
      message: >
        Off triggered at {{ now() }} by {{ trigger.entity_id }}, was {{ trigger.from_state.state }} is {{ trigger.to_state.state }}
          Light level is {{ states('sensor.pi3_living_room_multi_luminance') }}
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room
      option: 'Off'
