initial_state: 'on'
alias: 'Living room bedtime'
trigger:
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.home_occupied
      state: 'on'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room
      option: 'Bedtime'
