- platform: template
  sensors:
    battery_person1_mobile:
      value_template: '{{ states.device_tracker.person1_mobile.attributes.battery|default(0)|int() }}'
      icon_template: >
        {% set battery_level = states.device_tracker.person1_mobile.attributes.battery|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
