- platform: file
  name: grey_collection_date
  file_path: '/data/homeassistant/bin.grey.json'
  value_template: '{{ value_json.collection_date }}' 

- platform: file
  name: blue_collection_date
  file_path: '/data/homeassistant/bin.blue.json'
  value_template: '{{ value_json.collection_date }}' 

- platform: file
  name: brown_collection_date
  file_path: '/data/homeassistant/bin.brown.json'
  value_template: '{{ value_json.collection_date }}' 

- platform: template
  sensors:
    bin_grey:
      entity_id: sensor.office_multi_ultraviolet
      friendly_name: 'Grey bin collection'
      value_template: >-
        {% if (as_timestamp(now()) + ( 60 * 60 * 24 )) | timestamp_custom("%Y-%m-%d 00:00:00") == states('sensor.grey_collection_date') %}
          tomorrow 
        {% elif as_timestamp(now()) > as_timestamp(states('sensor.grey_collection_date'))+(60*60*12) %}
          past
        {% elif (as_timestamp(now()) | timestamp_custom("%Y-%m-%d 00:00:00")) == states('sensor.grey_collection_date') %}
          today
        {% else %}
          future
        {% endif %}

- platform: template
  sensors:
    bin_blue:
      entity_id: sensor.office_multi_ultraviolet
      friendly_name: 'Blue bin collection'
      value_template: >-
        {% if (as_timestamp(now()) + ( 60 * 60 * 24 )) | timestamp_custom("%Y-%m-%d 00:00:00") == states('sensor.blue_collection_date') %}
          tomorrow 
        {% elif as_timestamp(now()) > as_timestamp(states('sensor.blue_collection_date'))+(60*60*12) %}
          past
        {% elif (as_timestamp(now()) | timestamp_custom("%Y-%m-%d 00:00:00")) == states('sensor.blue_collection_date') %}
          today
        {% else %}
          future
        {% endif %}

- platform: template
  sensors:
    bin_brown:
      entity_id: sensor.office_multi_ultraviolet
      friendly_name: 'Brown bin collection'
      value_template: >-
        {% if (as_timestamp(now()) + ( 60 * 60 * 24 )) | timestamp_custom("%Y-%m-%d 00:00:00") == states('sensor.brown_collection_date') %}
          tomorrow 
        {% elif as_timestamp(now()) > as_timestamp(states('sensor.brown_collection_date'))+(60*60*12) %}
          past
        {% elif (as_timestamp(now()) | timestamp_custom("%Y-%m-%d 00:00:00")) == states('sensor.brown_collection_date') %}
          today
        {% else %}
          future
        {% endif %}
