- platform: template
  sensors:
    bin_brown:
      friendly_name: 'Brown bin collection'
      value_template: >-
        {% if (as_timestamp(now()) + ( 60 * 60 * 24 )) | timestamp_custom("%Y-%m-%d 00:00:00") == states('sensor.brown_collection_date') %}
          tomorrow 
        {% elif as_timestamp(now()) > as_timestamp(states('sensor.brown_collection_date'))+(60*60*12) %}
          past
        {% elif (as_timestamp(now()) | timestamp_custom("%Y-%m-%d 00:00:00")) == states('sensor.brown_collection_date') %}
          today
        {% elif states.sun.sun.state != None %}
          future
        {% else %}
          future
        {% endif %}
