- platform: darksky
  api_key: !secret darksky_api_key
  update_interval: '00:02:31'
  monitored_conditions:
    - summary
    - minutely_summary
    - hourly_summary
    - precip_type
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_cabineting
    - cloud_cover
    - visibility
    - icon
    - humidity
    - pressure
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
