- platform: google_travel_time
  name: 'person1s time to home'
  scan_interval: 4
  api_key: !secret google_travel_key
  origin: device_tracker.person1_mobile
  destination: !secret home_location
  options:
    mode: walking
