- platform: template
  sensors:
    person2_travel:
      friendly_name: "person2's location"
      value_template: '{% if is_state("group.person_person2", "not_home") -%} {{ states.sensor.person2s_time_to_home.attributes.duration }} to home{%- else -%} At {{ states("device_tracker.person2_mobile") }} {%- endif %}'
