- platform: template
  sensors:
    person3_travel:
      friendly_name: "person3's location"
      value_template: '{% if is_state("group.person_person3", "not_home") -%} {{ states.sensor.person3s_time_to_home.attributes.duration }} to home{%- else -%} At {{ states("device_tracker.person3_mobile") }} {%- endif %}'
