- platform: template
  sensors:
    person1_travel:
      friendly_name: "person1's location"
      value_template: >- 
        {% if is_state("group.person_person1", "not_home") -%} 
          {{ states.sensor.person1s_time_to_home.attributes.duration }} to home
        {% elif is_state("group.person_person1", "home") -%} 
          At home
        {%- else -%}
          At {{ states("device_tracker.person1_mobile") }}
        {%- endif %}
