- platform: template
  sensors:
    person3_travel:
      friendly_name: "person3's location"
      value_template: >-
        {% if is_state("group.person_person3", "home") %} 
          {{ states("input_select.person3_status_dropdown") }}
        {% elif not is_state("device_tracker.person3_mobile", "not_home") %}
          At {{ states("device_tracker.person3_mobile") }}
        {% else %}
          {{ states.sensor.person3s_time_to_home.attributes.duration }} to home
        {% endif %}
