- platform: template
  sensors:
    person1_travel:
      friendly_name: "person1's location"
      entity_id: input_boolean.person1_home, device_tracker.person1_mobile, sensor.person1s_time_to_home, input_select.person1_status_dropdown
      value_template: >- 
        {% if is_state("input_boolean.person1_home", "on") %} 
          {{ states("input_select.person1_status_dropdown") }}
        {% elif is_state("device_tracker.person1_mobile", "home") and is_state("input_boolean.person1_home", "off") %}
          Near home ({{ states("input_select.person1_status_dropdown") }})
        {% elif not is_state("device_tracker.person1_mobile", "not_home") %}
          At {{ states("device_tracker.person1_mobile") }}
        {% else %}
          {{ state_attr('sensor.person1s_time_to_home', 'duration')|round(0) }} {{ state_attr('sensor.person1s_time_to_home', 'unit_of_measurement') }} to home
        {% endif %}
