- platform: template
  sensors:
    zwave_battery_nodon_crc3100_octan_remote:
      value_template: "{{ state_attr('zwave.nodon_crc3100_octan_remote', 'battery_level')|default(75) }}"
      unit_of_measurement: "%"
