- platform: template
  sensors:
    zwave_battery_utility_door_exterior:
      value_template: "{{ state_attr('zwave.utility_door_exterior', 'battery_level')|default(75) }}"
      unit_of_measurement: "%"
