- platform: template
  sensors:
    zwave_battery_utility:
      value_template: '{{ states.zwave.utility.attributes.battery_level|default(75) }}'
      unit_of_measurement: "%"
      icon_template: >
        {% set battery_level = states.zwave.utility.attributes.battery_level | default(75) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
