- platform: template
  sensors: 
    garage_closed_bike:
      device_class: opening
      friendly_name: 'Garage door, bike'
      value_template: >- 
        {%- if is_state('binary_sensor.garage_closed_bike_sensor', 'on') and is_state('sensor.garage_closed_bike_access_control', '22') -%}
        on
        {%- else -%}
        off
        {%- endif -%}
