## Sensor that merges two sensors into one hopefully more reliable one (sometimes when closing, only one is updated)
- platform: template
  sensors: 
    garage_closed_car:
      device_class: opening
      friendly_name: 'Garage door, car'
      value_template: >- 
        {%- if is_state('sensor.garage_closed_car_access_control', '22') -%}
        on
        {%- else -%}
        off
        {%- endif -%}
