## Sensor that merges two sensors into one hopefully more reliable one (sometimes when closing, only one is updated)
- platform: template
  sensors: 
    garage_closed_car:
      device_class: garage_door
      friendly_name: 'Garage door, car'
      value_template: >- 
        {% if is_state('sensor.garage_closed_car_access_control', '22') and is_state('binary_sensor.garage_closed_car_sensor', 'on') %}
        True
        {% else %}
        False
        {% endif %}
