- platform: template
  sensors: 
    garage_closed_car:
      device_class: opening
      friendly_name: 'Garage door, car'
      value_template: >- 
        {%- if is_state('binary_sensor.garage_closed_car_sensor', 'on') and is_state('sensor.garage_closed_car_access_control', '22') -%}
        open
        {%- else -%}
        closed
        {%- endif -%}

