- platform: template
  sensors: 
    garden_lights_left_on:
      entity_id: sun.sun
      friendly_name: 'Garden lights left on'
      value_template: >-
        {% if is_state("switch.garden_lights_switch", "on" ) %} 
          {{ ( as_timestamp(now()) - as_timestamp(states.switch.garden_lights_switch.last_changed)|float ) > ( states.input_number.garden_time.state|float * 60 ) }}
        {% else %}
          False
        {% endif %}

