- platform: mqtt
  name: "Living room temperature"
  state_topic: 'homeassistant/sensor/living_room_multi_temperature/state'
  device_class: 'temperature'
  unit_of_measurement: '°C'
  unique_id: 'zwave-living_room_multi_temperature'
