- platform: mqtt
  name: "Office temperature"
  state_topic: 'homeassistant/sensor/office_multi_temperature/state'
  device_class: 'temperature'
  unit_of_measurement: '°C'
  unique_id: 'zwave-office_multi_temperature'
