alias: 'person1 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
      - device_tracker.3c_28_6d_da_eb_a1
      - device_tracker.person1_bt_mobile
      - device_tracker.person1_bt_front_mobile
    to: 'not_home'
  - platform: homeassistant
    event: start
condition:
  # As long as at least two trackers mark as away, they're away
  - condition: numeric_state
    entity_id: group.person_person1
    below: 2
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person1', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  # An exit door recently opened or closed
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.pi3_front_door_sensor.last_updated)) | int < 600 }}"
action:
  - service: script.person1_away
