initial_state: 'on'
alias: 'Resume music in the office'
trigger:
  - platform: state
    entity_id: calendar.person2_work
    to: 'off'
condition:
  - condition: state
    entity_id: media_player.office
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'on'
action:
  - service: media_player.media_play_pause
    data:
      entity_id: media_player.office
