alias: 'Home not occupied'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person3_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.person2_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.person1_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.person1_tablet_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.person4_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
condition:
  condition: and
  conditions:
    # We're all away
    - condition: state
      entity_id: input_boolean.person3_home
      state: 'off'
    - condition: state
      entity_id: input_boolean.person2_home
      state: 'off'
    - condition: or
      conditions:
      # Either the phone or tablet are away
      - condition: state
        entity_id: input_boolean.person1_tablet_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.person1_home
        state: 'off'
    - condition: state
      entity_id: input_boolean.person4_home
      state: 'off'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.home_occupied
  - service: automation.turn_on
    data:
      entity_id: automation.garage_open_nobody_home
