alias: 'Home occupied'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person3_home
    to: 'on'
  - platform: state
    entity_id: input_boolean.person2_home
    to: 'on'
  - platform: state
    entity_id: input_boolean.person1_home
    to: 'on'
  - platform: state
    entity_id: input_boolean.person4_home
    to: 'on'
  - platform: state
    entity_id: input_boolean.family_room_occupied
    to: 'on'
  - platform: state
    entity_id: input_boolean.living_room_occupied
    to: 'on'
  - platform: state
    entity_id: input_boolean.office_occupied
    to: 'on'
  - platform: state
    entity_id: input_boolean.person1_tablet_home
    to: 'on'
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.home_occupied
