alias: 'Telegram callback'
initial_state: 'on'
trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: "/trains"
action:
  - service: script.telegram_trains
  - service: telegram_bot.answer_callback_query
    data_template:
      message: "{{ states('input_text.telegram_message') }}"
      callback_query_id: "{{ trigger.event.data.id }}"
