- platform: generic_thermostat
  name: Living room
  heater: input_boolean.living_room_heater
  target_sensor: sensor.living_room_multi_temperature
  cold_tolerance: 10
  initial_operation_mode: auto
