- platform: here_travel_time
  name: "person2s time to home"
  scan_interval: 604800
  app_id: !secret  here_app_id
  app_code: !secret here_app_code
  origin: device_tracker.person2_mobile_gps
  destination: zone.home
  mode: car
  traffic_mode: true
