- platform: here_travel_time
  name: "person3s time to home by bus"
  scan_interval: 604800
  app_id: !secret  here_app_id
  app_code: !secret here_app_code
  origin: device_tracker.person3_mobile
  destination: zone.home
  mode: publicTransportTimeTable
