alias: 'Extractor notification'
trigger:
  - platform: numeric_state
    entity_id: sensor.master_ensuite_humidity
    above: 80
    for: '00:01:00'
condition:
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'on'
action:
  # Wait for it to go back down, or an hour to pass
  - wait_template: "{{ (states('sensor.master_ensuite_humidity')|int) < 60 }}"
    timeout: '01:00:00'
    continue_on_timeout: 'false'
  - service: notify.logfile
    data:
      message: "SENDME You can turn the extractor fan off now"
