alias: 'Adults away doors open'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.adults_away
    from: 'off'
    to: 'on'
condition:
  condition: and
  conditions: 
    - condition: state
      entity_id: group.outside_doors
      state: 'on'
    - condition: state
      entity_id: group.tv
      state: 'not_home'
action:
  - service: notify.person3
    data_template: 
      message: >
        The following doors are open: 
        {%- for entity_id in states.group.outside_doors.attributes.entity_id -%}
          {% set parts = entity_id.split('.') -%}
          {%- if states(entity_id) == 'on' %}
          {%- if loop.first %} {% elif loop.last %} and the {% else %}, the {% endif -%}{{ states[parts[0]][parts[1]].name }}{% endif -%}
        {%- endfor %}
  - service: notify.person2
    data_template: 
      message: >
        The following doors are open: 
        {%- for entity_id in states.group.outside_doors.attributes.entity_id -%}
          {% set parts = entity_id.split('.') -%}
          {%- if states(entity_id) == 'on' %}
          {%- if loop.first %} {% elif loop.last %} and the {% else %}, the {% endif -%}{{ states[parts[0]][parts[1]].name }}{% endif -%}
        {%- endfor %}
