#
initial_state: 'on'
alias: 'Adults home lights on'
trigger:
  - platform: state
    entity_id: input_boolean.adults_away
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.all_away
    from: 'on'
    to: 'off'
condition:
  condition: and
  conditions: 
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.living_room_multi_luminance
      below: 11
    - condition: state
      entity_id: switch.cabinet_light_switch
      state: 'off'
      for:
        minutes: 5
    - condition: and
      conditions:
        - condition: time
          after: '14:00:00'
          before: '23:00:00'
action:
  - service: light.turn_on
    data:
      entity_id: light.hall
      transition: 30
      brightness: 15
  - service: scene.turn_on
    entity_id: scene.lounge_lights_on
  - wait_template: "{{ states('light.hall') != 'unavailable' }}"
  - condition: state
    entity_id: light.hall
    state: 'off'
  - service: light.turn_on
    data:
      entity_id: light.hall
      transition: 30
      brightness: 15
