alias: 'Adults returned'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: group.my_adults
    from: 'not_home'
    to: 'home'
condition:
  - condition: state
    entity_id: input_boolean.adults_away
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.adults_away
  - service: input_boolean.turn_off
    entity_id: input_boolean.alarm_mode
