alias: 'All away lights off'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: group.my_adults
    from: 'home'
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: device_tracker.livingroom_chromecast
      state: 'not_home'
    - condition: state
      entity_id: media_player.samsung_tv_remote
      state: 'off'
action:
  service: scene.turn_on
  entity_id: scene.all_lights_off
