alias: 'All away lights off'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.adults_away
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: input_boolean.all_away
    to: 'on'
    from: 'off'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: device_tracker.family_tv
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.livingroom_chromecast
      state: 'not_home'
    - condition: state
      entity_id: media_player.samsung_tv_remote
      state: 'off'
action:
  - service: scene.turn_on
    entity_id: scene.all_lights_off
