alias: 'All away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: group.my_family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
condition:
  condition: and
  conditions:
    # TVs
    - condition: state
      entity_id: device_tracker.family_tv
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.livingroom_chromecast
      state: 'not_home'
    - condition: state
      entity_id: media_player.samsung_tv_remote
      state: 'off'
    # Media players
    - condition: state
      entity_id: media_player.office
      state: 'paused'
    - condition: state
      entity_id: media_player.family_room
      state: 'paused'
    - condition: state
      entity_id: media_player.living_room
      state: 'paused'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.all_away
