alias: 'All returned'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: group.my_family
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: group.my_adults
    from: 'not_home'
    to: 'home'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.all_away
  - service: input_boolean.turn_off
    entity_id: input_boolean.alarm_mode
