initial_state: 'on'
alias: 'Battery garage door closed car'
trigger:
  - platform: numeric_state
    entity_id: zwave.garage_door_closed_car
    value_template: "{{ states.zwave.garage_door_closed_car.attributes.battery_level }}"
    below: 25
  - platform: numeric_state
    entity_id: zwave.garage_door_closed_car
    value_template: "{{ states.zwave.garage_door_closed_car.attributes.battery_level }}"
    below: 10
  - platform: numeric_state
    entity_id: zwave.garage_door_closed_car
    value_template: "{{ states.zwave.garage_door_closed_car.attributes.battery_level }}"
    below: 5
action:
  service: notify.person2
  data:
    message: "The garage door sensor for the car is at {{ states.zwave.garage_door_closed_car.attributes.battery_level }}% battery, it uses a ER14250 battery"
