alias: 'Bedhead light on night'
initial_state: 'on'
trigger:
  platform: state
  entity_id: light.master_bedroom_bedhead
  to: 'on'
  for: 
    minutes: 60
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: media_player.person2
      state: 'off'
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
action:
  - service: light.turn_off
    data:
      entity_id: light.master_bedroom_bedhead
      transition: 30
