initial_state: 'off'
alias: 'Bin collection check'
trigger:
  - platform: state
    entity_id: 'sensor.bin_collection_type'
  - platform: time
    at: '02:20:22'
  - platform: homeassistant
    event: shutdown
action:
  service: notify.logfile
  data_template:
    message: '{ "collection_date":"{{ states("sensor.bin_collection_day") }}", "collection_type":"{{ states("sensor.bin_collection_type") }}","timestamp":"{{ now() }}" }'
