initial_state: 'on'
alias: 'Bin collection check'
trigger:
  - platform: state
    entity_id: 'sensor.bin_collection_type'
action:
  service: notify.logfile
  data_template:
    message: '{ "collection_date":"{{ states("sensor.bin_collection_day") }}", "collection_type":"{{ states("sensor.bin_collection_type") }}" }'
