alias: 'Clear states'
initial_state: 'on'
trigger:
  platform: time
  at: '12:00:00'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_is_awake
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_is_awake
  - service: switch.turn_on
    entity_id: switch.fluxer
