initial_state: 'on'
alias: 'Darker TV on'
trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    below: 11
  - platform: state
    entity_id: media_player.samsung_tv_remote
    from: 'off'
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.tv_light_switch
      state: 'off'
    - condition: state
      entity_id: media_player.samsung_tv_remote
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.living_room_multi_luminance
      below: 11
    - condition: state
      entity_id: group.my_adults
      state: 'home'
    - condition: time
      after: '04:00:00'
      before: '23:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.lounge_lights_on
