initial_state: 'on'
alias: 'Dark TV on'
trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    below: 18
  - platform: state
    entity_id: media_player.samsung_tv_remote
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
  - platform: state
    entity_id: device_tracker.livingroom_chromecast
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.tv_light_switch
      state: 'off'
      for:
        minutes: 5
    - condition: numeric_state
      entity_id: sensor.living_room_multi_luminance
      below: 18
    - condition: state
      entity_id: input_boolean.adults_away
      state: 'off'
    - condition: time
      after: '04:00:00'
      before: '23:00:00'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.samsung_tv_remote
        state: 'on'
      - condition: state
        entity_id: media_player.living_room_tv
        state: 'playing'
      - condition: state
        entity_id: device_tracker.livingroom_chromecast
        state: 'home'
action:
  - service: homeassistant.turn_off
    entity_id: automation.lounge_in_daylight_2
  - service: switch.turn_on
    entity_id: switch.tv_light_switch
  - delay: 00:00:10
  - service: homeassistant.turn_on
    entity_id: automation.lounge_in_daylight_2
