initial_state: 'on'
alias: 'Hall lights off'
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: 5
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: switch.hall_downstairs_switch
      state: 'on'
action:
  - service: switch.turn_off
    entity_id: switch.hall_downstairs_switch
  - delay: 00:01:00
  - condition: state
    entity_id: switch.hall_downstairs_switch
    state: 'on'
  - service: switch.turn_off
    entity_id: switch.hall_downstairs_switch
