initial_state: 'on'
alias: 'Hall lights off departure'
trigger:
  - platform: state
    entity_id: input_boolean.person2_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.person1_home
    to: 'off'
condition:
  - condition: state
    entity_id: switch.hall_downstairs_switch
    state: 'on'
  - condition: state
    entity_id: input_boolean.person2_home
    state: 'off'
  - condition: state
    entity_id: input_boolean.person1_home
    state: 'off'
action:
  - service: switch.turn_off
    entity_id: switch.hall_downstairs_switch
  - delay: 00:01:00
  - condition: state
    entity_id: switch.hall_downstairs_switch
    state: 'on'
  - service: switch.turn_off
    entity_id: switch.hall_downstairs_switch
