initial_state: 'on'
alias: 'Hall lights on'
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 5
  - platform: state
    entity_id: input_boolean.all_away
    to: 'off'
condition:
  - condition: state
    entity_id: switch.hall_downstairs_switch
    state: 'off'
  - condition: state
    entity_id: input_boolean.all_away
    state: 'off'
  - condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 5
action:
  - service: switch.turn_on
    entity_id: switch.hall_downstairs_switch
  - delay: 00:01:00
  - condition: state
    entity_id: switch.hall_downstairs_switch
    state: 'off'
  - service: switch.turn_on
    entity_id: switch.hall_downstairs_switch
