initial_state: 'on'
alias: 'Hall lights on'
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 5
  - platform: state
    entity_id: input_boolean.all_away
    to: 'off'
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'off'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: switch.hall_downstairs_switch
      state: 'off'
    - condition: state
      entity_id: input_boolean.all_away
      state: 'off'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: 5
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'on'
action:
  - service: switch.turn_on
    entity_id: switch.hall_downstairs_switch
  - delay: 00:01:00
  - condition: state
    entity_id: switch.hall_downstairs_switch
    state: 'off'
  - service: switch.turn_on
    entity_id: switch.hall_downstairs_switch
