initial_state: 'on'
alias: 'Hall lights off departure'
trigger:
  - platform: state
    entity_id: input_boolean.all_away
    to: 'on'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: light.hall
      state: 'on'
action:
  - service: light.turn_off
    data:
      entity_id: light.hall
      transition: 10
  - delay: 00:01:00
  - condition: state
    entity_id: light.hall
    state: 'on'
  - service: light.turn_off
    data:
      entity_id: light.hall
      transition: 10
