initial_state: 'on'
alias: 'Hall lights off'
trigger:
  - platform: numeric_state
    entity_id: sensor.sun_elevation
    above: 5
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
    for:
      minutes: 2
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    above: 80
    for:
      minutes: 5
## Also need to turn off if we've got up in the night and gone back to bed
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: light.hall
      state: 'on'
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.sun_elevation
        above: 5
      - condition: numeric_state
        entity_id: sensor.living_room_multi_luminance
        above: 50
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.bedtime
          state: 'on'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
action:
  - wait_template: "{{ states('light.hall') != 'unavailable' }}"
  - service: light.turn_off
    data:
      entity_id: light.hall
      transition: 30
  - delay: 00:01:00
  - wait_template: "{{ states('light.hall') != 'unavailable' }}"
  - condition: state
    entity_id: light.hall
    state: 'on'
  - service: light.turn_off
    data:
      entity_id: light.hall
      transition: 30
