initial_state: 'on'
alias: 'Hall lights on'
trigger:
  - platform: numeric_state
    entity_id: sensor.sun_elevation
    below: 5
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'off'
  - platform: state
    entity_id: input_boolean.adults_away
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.all_away
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.lighting_automations
    to: 'on'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: light.hall
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.sun_elevation
      below: 5
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.all_away
        state: 'off'
      - condition: state
        entity_id: input_boolean.adults_away
        state: 'off'
action:
  - service: light.turn_on
    data:
      entity_id: light.hall
      transition: 30
      brightness: 25
  - delay: 00:01:00
  - condition: state
    entity_id: light.hall
    state: 'off'
  - service: light.turn_on
    data:
      entity_id: light.hall
      transition: 30
      brightness: 25
