initial_state: 'on'
alias: 'Hall lights off'
trigger:
  - platform: numeric_state
    entity_id: sensor.sun_elevation
    above: 5
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
    for:
      minutes: 5
## Also need to turn off if we've got up in the night and gone back to bed
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: switch.hall_downstairs_switch
      state: 'on'
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.sun_elevation
        above: 5
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.bedtime
          state: 'on'
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
action:
  - service: switch.turn_off
    entity_id: switch.hall_downstairs_switch
  - delay: 00:01:00
  - condition: state
    entity_id: switch.hall_downstairs_switch
    state: 'on'
  - service: switch.turn_off
    entity_id: switch.hall_downstairs_switch
