initial_state: 'on'
alias: 'Lounge in daylight'
trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    above: 75
  - platform: numeric_state
    entity_id: sensor.living_room_multi_luminance
    above: 30
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    # Lights are on
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
    - condition: or
      conditions:
        # Very bright, or...
      - condition: numeric_state
        entity_id: sensor.living_room_multi_luminance
        above: 70
        # Sun is rising
      - condition: state
        entity_id: binary_sensor.trend_sun_elevation
        state: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.lounge_lights_off
