initial_state: 'on'
alias: 'Lounge in daylight'
trigger:
  platform: numeric_state
  entity_id: sensor.living_room_multi_luminance
  above: 75
condition:
  condition: state
  entity_id: group.living_room_lights
  state: 'on'
  for:
    minutes: 1
action:
  service: scene.turn_on
  entity_id: scene.lounge_lights_off
