initial_state: 'on'
alias: 'Number on at sunset'
trigger:
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.number_sign_switch
      state: 'off'
    - condition: time
      after: '12:00:00'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
action:
  service: switch.turn_on
  entity_id: switch.number_sign_switch
