alias: Mark person as just left
trigger:
  - platform: state
    entity_id: group.person_person2
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: group.person_person3
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: group.person_person1
    from: 'home'
    to: 'not_home'
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'group.person_person2' %}
          input_select.person2_status_dropdown
        {% elif trigger.entity_id == 'group.person_person3' %}
          input_select.person3_status_dropdown
        {% else %}
          input_select.person1_status_dropdown
        {% endif %}
      option: Just Left
