alias: Mark person as just arrived
trigger:
  - platform: state
    entity_id: group.person_person2
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: group.person_person3
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: group.person_person1
    from: 'not_home'
    to: 'home'
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'group.person_person2' %}
          input_select.person2_status_dropdown
        {% elif trigger.entity_id == 'group.person_person3' %}
          input_select.person3_status_dropdown
        {% else %}
          input_select.person1_status_dropdown
        {% endif %}
      option: >
        {% if trigger.entity_id == 'group.person_person2' %}
          {% if states.input_select.person2_status_dropdown.state == 'Just Left' %}
            Home
          {% else %}
            Just Arrived
          {% endif %}
        {% elif trigger.entity_id == 'group.person_person3' %}
          {% if states.input_select.person3_status_dropdown.state == 'Just Left' %}
            Home
          {% else %}
            Just Arrived
          {% endif %}
        {% else %}
          {% if states.input_select.person1_status_dropdown.state == 'Just Left' %}
            Home
          {% else %}
            Just Arrived
          {% endif %}
        {% endif %}
