alias: 'person1 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id:
    - device_tracker.person1_mobile_wifi
    - device_tracker.person1_mobile
    - device_tracker.person3_mobile_bt
    to: 'not_home'
    for:
      minutes: 5
  - platform: homeassistant
    event: start
condition:
  - condition: numeric_state
    entity_id: group.person_person1
    below: 2
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person1', 'entity_id'))|list)|groupby('state'))['home']|count }}"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person1_home
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_is_awake
