alias: 'person2 asleep'
initial_state: 'on'
trigger:
  platform: state
  entity_id: light.master_bedroom_bedhead
  to: 'off'
  for: 
    minutes: 5
condition:
  - condition: time
    after: '22:00:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_is_awake
