initial_state: 'on'
alias: 'person2 coming home'
trigger:
  - platform: state
    entity_id: device_tracker.person2_mobile
    to: 'home station'
condition:
  - condition: and
    conditions:
      - condition: time
        after: '15:00:00'
      - condition: state
        entity_id: group.my_adults
        state: 'not_home'
action:
  - service: notify.push_person2_phone
    data:
      message: "Nobody's home right now"
  - service: homeassistant.turn_off
    entity_id: automation.person2_coming_home
