alias: 'person3 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id:
    - device_tracker.person3_mobile_wifi
    - device_tracker.person3_mobile
    - device_tracker.nexus_5x
    to: 'not_home'
    for:
      minutes: 2
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.person3_home
    state: 'on'
  - condition: numeric_state
    entity_id: group.person_person3
    below: 2
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person3', 'entity_id'))|list)|groupby('state'))['home']|count }}"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person3_home
  - service: input_boolean.turn_on
    entity_id: input_boolean.person3_is_awake
