alias: 'person1 up reminder'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person1_is_awake
    to: 'on'
    for:
      minutes: 3
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.person_person1
      state: 'home'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: calendar.person1_holiday
      state: 'off'
action:
  - service: media_player.turn_on
    data:
      entity_id: media_player.cast_second_bedroom_speaker
  - delay: '00:00:05'
  - service: media_player.volume_set
    data:
      entity_id: media_player.cast_second_bedroom_speaker
      volume_level: 0.3
  - service: tts.google_say
    entity_id: media_player.cast_second_bedroom_speaker
    data:
      message: "Hi person1, if you're not already up, time to get moving."
  - delay: '00:03:00'
  - service: media_player.volume_set
    data:
      entity_id: media_player.cast_second_bedroom_speaker
      volume_level: 0.4
  - service: tts.google_say
    entity_id: media_player.cast_second_bedroom_speaker
    data:
      message: "Hi person1, if you're not already up, time to get moving."
