alias: 'person1 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: group.person_person1
    from: 'home'
    to: 'not_home'
    for:
      minutes: 2
  - platform: homeassistant
    event: start
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.person_person1
      state: 'not_home'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person1_home
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_is_awake
