alias: 'person2 up'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.person2
    to: 'playing'
  - platform: state
    entity_id: light.master_bedroom_bedhead
    to: 'on'
    for:
      minutes: 1
  - platform: state
    entity_id: group.person_person2
    to: 'not_home'
    for:
      minutes: 5
condition:
  - condition: or
    conditions:
    - condition: time
      after: '04:00:00'
    - condition: state
      entity_id: group.person_person2
      state: 'not_home'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_is_awake
