alias: 'person1 asleep'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.person1
    from: 'playing'
    to: 'off'
    for:
      minutes: 5
  - platform: time
    at: '23:00:00'
condition:
  - condition: state
    entity_id: group.person_person1
    state: 'home'
  - condition: time
    after: '20:00:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person1_is_awake
