initial_state: 'on'
alias: 'person3 home'
trigger:
  - platform: state
    entity_id: group.person_person3
    from: 'not_home'
    to: 'home'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: group.person_person3
    state: 'home'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person3_travelling
  - service: input_boolean.turn_on
    entity_id: input_boolean.person3_home
