initial_state: 'on'
alias: 'person1 returning'
trigger:
  platform: state
  entity_id: device_tracker.person1_mobile
  from: 'work'
  to: 'not_home'
  for:
    minutes: 10
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.my_adults
      state: 'home'
    - condition: or
      conditions: 
      - condition: time
        after: '15:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
      - condition: time
        after: '12:00:00'
        weekday:
          - fri
action:
  - wait_template: "{{ states('sensor.person1s_time_to_home') < 8 }}"
    timeout: 00:10:00
  - service: notify.lametric_info
    data_template:
      message: "person1 should be home from work in about {{ states('sensor.person1s_time_to_home') }} to {{ states('sensor.person1s_time_to_home')|int + 15 }} minutes"
