alias: 'person2 up bedhead light on'
initial_state: 'on'
trigger:
  platform: state
  entity_id: media_player.person2
  to: 'playing'
condition:
  condition: time
  before: '10:00:00'
action:
  - service: light.turn_on
    data:
      entity_id: light.master_bedroom_bedhead
      transition: 30
      brightness_pct: 100
      color_name: white
