alias: 'person2 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: group.person_person2
    to: 'not_home'
    for:
      minutes: 2
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: group.person_person2
    state: 'not_home'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_home
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_is_awake
