alias: 'person1 asleep'
initial_state: 'on'
trigger:
  platform: state
  entity_id: media_player.person1
  from: 'playing'
  to: 'off'
  for:
    minutes: 5
condition:
  - condition: time
    after: '20:00:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person1_is_awake
