alias: 'person3 up'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.samsung_tv_remote
    to: 'on'
  - platform: state
    entity_id: device_tracker.livingroom_chromecast
    to: 'home'
  - platform: state
    entity_id: input_select.person3_status_dropdown
    to: 'Away'
  - platform: state
    entity_id: binary_sensor.utility_door_exterior_sensor
    to: 'on'
condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.person3_is_awake
        state: 'off'
      - condition: state
        entity_id: binary_sensor.utility_door_exterior_sensor
        state: 'on'
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.person3_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.person3_travelling
        state: 'off'
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.person3_home
        state: 'on'
      - condition: or
        conditions:
        - condition: time
          after: '04:00:00'
          before: '18:00:00'
        - condition: state
          entity_id: media_player.samsung_tv_remote
          state: 'on'
        - condition: state
          entity_id: device_tracker.livingroom_chromecast
          state: 'home'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person3_is_awake
