alias: 'person3 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id:
    - device_tracker.person3_mobile
    - device_tracker.nexus_5x
    to: 'not_home'
  - platform: state
    entity_id:
    - device_tracker.person3_mobile_wifi
    to: 'not_home'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.person3_home
    state: 'on'
  - condition: numeric_state
    entity_id: group.person_person3
    below: 2
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person3', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  - condition: or
    conditions:
    # A door was opened in the last 6 minutes
    - condition: template
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states.sensor.last_opened.last_updated)) | int < 360 }}"
    # A door is currently open
    - condition: state
      entity_id: binary_sensor.front_door_sensor
      state: 'on'
    - condition: state
      entity_id: binary_sensor.patio_door_left_sensor
      state: 'on'
    - condition: state
      entity_id: binary_sensor.utility_door_exterior_sensor
      state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person3_home
  - service: input_boolean.turn_on
    entity_id: input_boolean.person3_is_awake
