alias: 'person2 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
    - device_tracker.404e36245315
    - device_tracker.serenity
    - device_tracker.person2_mobile_gps
    to: 'not_home'
    for:
      minutes: 2
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.person2_home
    state: 'on'
  - condition: numeric_state
    entity_id: group.person_person2
    below: 2
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person2', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  # Should require sensor.last_opened to have recently been updated
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_home
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_is_awake
