alias: 'person1 up'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.person1
    to: 'playing'
  - platform: state
    entity_id: sensor.person1
    to: 'Online'
  - platform: state
    entity_id: group.person_person1
    to: 'not_home'
    for:
      minutes: 5
condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.person_person1
      state: 'not_home'
    - condition: and
      conditions:
      - condition: state
        entity_id: group.person_person1
        state: 'home'
      - condition: time
        before: '10:00:00'
      - condition: state
        entity_id: media_player.person1
        state: 'playing'
    - condition: and
      conditions:
      - condition: state
        entity_id: group.person_person1
        state: 'home'
      - condition: time
        before: '12:00:00'
      - condition: state
        entity_id: sensor.person1
        state: 'Online'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_is_awake
