alias: 'person3 up'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.samsung_tv_remote
    to: 'on'
  - platform: state
    entity_id: group.person_person3
    to: 'not_home'
    for:
      minutes: 5
  - platform: state
    entity_id: sensor.utility_door
    to: 'open'
condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.person3_is_awake
        state: 'off'
      - condition: state
        entity_id: sensor.utility_door
        state: 'open'
    - condition: and
      conditions:
      - condition: state
        entity_id: group.person_person3
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.person3_travelling
        state: 'off'
    - condition: and
      conditions:
      - condition: state
        entity_id: media_player.samsung_tv_remote
        state: 'on'
      - condition: state
        entity_id: group.person_person3
        state: 'home'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person3_is_awake
