initial_state: 'on'
alias: 'Return train status'
trigger:
  platform: time
  at: '16:35:00'
condition:
  condition: and
  conditions: 
    - condition: zone
      zone: zone.work
      entity_id: device_tracker.person2_mobile
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
action:
  service: notify.push_person2_phone
  data_template: 
      message: "{{ states.sensor.trains_from_station.state }}"

