alias: 'Season is winter'
initial_state: 'on'
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: '03:00:00'
condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ states("input_select.season") != "Christmas" }}'
    - condition: template
      value_template: '{{ ( now().month == 12 ) or ( now().month < 3 ) }}'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.season
      option: Winter
