initial_state: 'on'
alias: 'Stop classical music in the office'
trigger:
  platform: state
  entity_id: device_tracker.work_laptop
  to: 'not_home'
  for:
    minutes: 2
action:
  service: media_player.media_pause
  data:
    entity_id: media_player.office
