alias: 'Test notify'
initial_state: 'off'
trigger:
  - platform: time
    at: '14:00:00'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.cast_kitchen_speaker
      media_content_id: http://pi3.family:8123/local/sounds/sub_alert.mp3
      media_content_type: music
