alias: 'Test notify'
initial_state: 'off'
trigger:
  platform: time
  at: '14:00:00'
action:
  - service: media_player.sonos_snapshot
  - service: media_player.play_media
    data:
      entity_id: media_player.office, media_player.family_room, media_player.living_room
      media_content_id: http://pi3.family:8123/local/sounds/wind_chime.mp3
      media_content_type: music
  - delay: '00:00:01'
  - service: tts.google_say
    entity_id: media_player.office, media_player.family_room, media_player.living_room
    data:
      message: "This is a test"
  - service: media_player.sonos_restore
