alias: 'Utility door open after sunset turn off'
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.utility_door
  to: 'closed'
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -5
    - condition: state
      entity_id: switch.garden_lights_switch
      state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: switch.garden_lights_switch
