alias: 'Utility door open after sunset turn off'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.utility_door
    to: 'closed'
  - platform: state
    entity_id: binary_sensor.patio_door_left_sensor
    to: 'off'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.sun_elevation
      below: -5
    - condition: state
      entity_id: switch.garden_lights_switch
      state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: switch.garden_lights_switch
