alias: 'Wake person1'
initial_state: 'off'
trigger:
  platform: time
  at: '07:50:00'
condition:
  condition: state
  entity_id: input_boolean.person1_is_awake
  state: 'off'
action:
  - service: media_player.turn_on
    entity_id: media_player.cast_second_bedroom_speaker
  - service: media_player.media_play
    entity_id: media_player.cast_second_bedroom_speaker
    data:
      media_content_type: music
      media_content_id: tbc
