alias: 'Winter lights off'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.all_away
    from: 'off'
    to: 'on'
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: input_select.season
      state: 'Winter'
action:
  - service: switch.turn_off
    entity_id:
      - switch.hall_downstairs_switch
  - delay: '00:01:00'
  - service: switch.turn_off
    entity_id:
      - switch.hall_downstairs_switch
