alias: 'Winter lights off season'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.season
    from: 'Winter'
condition:
  - condition: state
    entity_id: input_boolean.lighting_automations
    state: 'on'
  - condition: state
    entity_id: light.hall
    state: 'on'
action:
  - service: light.turn_off
    data:
      entity_id: light.hall
      transition: 30
  - delay: '00:01:00'
  - service: light.turn_off
    data:
      entity_id: light.hall
      transition: 30
