alias: 'Winter lights on'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'off'
  - platform: state
    entity_id: input_boolean.adults_away
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_boolean.all_away
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_select.season
    to: 'Winter'
condition:
  - condition: state
    entity_id: input_select.season
    state: 'Winter'
  - condition: time
    after: '05:00:00'
    before: '22:00:00'
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.adults_away
        state: 'off'
      - condition: state
        entity_id: input_boolean.all_away
        state: 'off'
action:
  - service: switch.turn_on
    entity_id:
      - switch.hall_downstairs_switch
  - delay: '00:01:00'
  - service: switch.turn_on
    entity_id:
      - switch.hall_downstairs_switch
