initial_state: 'on'
alias: 'person2 not driving'
trigger:
  - platform: event
    event_type: tasker_webhook
    event_data:
      who: person2
condition: 
  # Leaving, the car
  - condition: template
    value_template: >-
      {{ 'Exit Car' in trigger.event.data.what }}
  # Driving
  - condition: state
    entity_id: input_boolean.person2_driving
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_driving
