alias: 'person2 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
      - device_tracker.40_4e_36_24_53_15
      - device_tracker.person2_bt_mobile
      - device_tracker.person2_bt_front_mobile
    to: 'not_home'
  - platform: homeassistant
    event: start
condition:
  - condition: numeric_state
    entity_id: group.person_person2
    above: 1
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person2', 'entity_id'))|list)|groupby('state'))['not_home']|count }}"
  # An exit door recently opened or closed
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.front_door_sensor.last_updated)) | int < 600 }}"
action:
  - service: script.person2_away
