alias: 'person2 up'
initial_state: 'on'
trigger:
  # Music is playing
  - platform: state
    entity_id: 
      - media_player.master_bedroom_speaker
      - media_player.person2
    to: 'playing'
  # Phone or tablet is unplugged
  - platform: state
    entity_id: 
      - input_boolean.person2_phone_charging
      - input_boolean.person2_tablet_charging
    to: 'off'
  # Bedhead light is on
  - platform: state
    entity_id: 
      - light.master_bedroom_bedhead
      - light.yeelight_strip1_286c07afc307
    to: 'on'
    for:
      minutes: 1
condition:
  - condition: state
    entity_id: input_boolean.person2_in_bed
    state: 'on'
  - condition: state
    entity_id: input_boolean.person2_home
    state: 'on'
  - condition: time
    after: '03:00:00'
    before: '21:00:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_in_bed
  - service: notify.logfile
    data_template:
      message: >
        Turned off person2 in bed because the {{ trigger.to_state.name }} was {{ trigger.to_state.state }} at {{ now() }}

