- platform: mqtt
  name: "Garage door car"
  state_topic: 'homeassistant/binary_sensor/garage_closed_car_sensor/state'
  payload_on: 'on'
  payload_off: 'off'
  device_class: 'garage_door'
  unique_id: 'zwave-garage_closed_car_sensor'
