initial_state: 'on'
alias: 'person4 home'
trigger:
  - platform: state
    entity_id:
    - device_tracker.00_1d_29_a5_49_ae
    - device_tracker.person4_bt_front_mobile
    - device_tracker.person4_bt_mobile
    to: 'home'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.person4_home
    state: 'off'
action:
  - service: script.person4_home
