initial_state: 'on'
alias: 'BT front offline too long'
trigger:
  - platform: state
    entity_id: binary_sensor.first_floor_front
    to: 'off'
    for: '00:10:00'
action:
  - wait_template: >-
      {{ is_state('input_boolean.person2_is_awake','on') }}
  - service: notify.person2_telegram
    data:
      message: "Front Bluetooth node is a zombie, please resurrect it"
  - wait_template: >-
      {{ is_state('binary_sensor.first_floor_front','on') }}
  - service: notify.person2_telegram
    data:
      message: "Front Bluetooth node is alive again!"
