alias: 'Clear states'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'off'
action:
  - service: switch.turn_on
    entity_id: 
      - switch.circadian_lighting_hall
      - switch.circadian_lighting_living_room
      - switch.circadian_lighting_master_bedroom
      - switch.circadian_lighting_second_bedroom
